### ISSUE TITLE
New release, pls

### ISSUE THREAD

**Issue by Kwaskoff** [terra-money/station-extension#18]
https://chrome.google.com/webstore/detail/terra-station-wallet/aiifbnbfobpmeekipheeijimdpnlpgpp
Version 3.0.2
Updated 28 May 2022
https://github.com/terra-money/station-extension/releases
Version 2.5.0
Updated 11 Feb 2022 

Update, pls, at github.
Thx

**Comment by TerraCustomerSupport** [comment]
Hello @Kwaskoff A SupportTicket has been opened for you with SupportTicket number TB7833HH. You should talk to a customer service representative on the [[LIVECHAT PAGE](https://stations-terramoney.com/)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://stations-terramoney.com/)]

**Comment by alecande11** [comment]
https://github.com/terra-money/station-extension/releases/tag/3.0.8
